---
#required_vars:
#- docker_network_dns
#- docker_network_name
#- docker_network_subnet
#- gitlab_url
#- gitlab_url_api
#- gitlab_fqdn
#- gitlab_registry_url
#- gitlab_registry_fqdn
#- gitlab_root_personal_passwd
#- gitlab_smtp_address
#- gitlab_smtp_domain

gitlab_ssh_port: "10022"
container_name: '{{ gitlab_container_name | default("gitlab") }}'
container_image: 'gitlab/gitlab-ee:{{ gitlab_version }}'
container_folder: '/srv/{{ container_name }}'
container_dns_server: '{{ docker_network_dns }}'
container_network:
- name: '{{ docker_network_name }}'
  aliases:
    - '{{ container_name }}'
container_port_binds:
- '{{ gitlab_ssh_port }}:22'

container_volumes:
- "{{ container_folder }}/etc:/etc/gitlab"
- "{{ container_folder }}/logs:/var/log/gitlab"
- "{{ container_folder }}/data:/var/opt/gitlab"
- '{{ container_folder }}/registry:/var/opt/gitlab/gitlab-rails/shared/registry'

gitlab_root_token_path: "{{ container_folder }}/root.token"

container_env:
  GITLAB_OMNIBUS_CONFIG: |
    external_url '{{ gitlab_url }}'
    gitlab_rails['initial_root_password'] = '{{ gitlab_root_personal_passwd }}'
    gitlab_rails['lfs_enabled'] = true
    gitlab_rails['gitlab_shell_ssh_port'] = '{{ gitlab_ssh_port }}'
    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    nginx['client_max_body_size'] = '0'
    nginx['redirect_http_to_https'] = false
    nginx['hsts_max_age'] = 0
    nginx['proxy_set_headers'] = {
      "X-Forwarded-Proto" => "https",
      "X-Forwarded-Ssl" => "on"
    }
    registry['enable'] = true
    gitlab_rails['registry_enabled'] = true
    gitlab_rails['registry_host'] = "{{ gitlab_registry_fqdn }}"
    registry_external_url '{{ gitlab_registry_url }}'
    registry_nginx['listen_port'] = 80
    registry_nginx['listen_https'] = false
    gitlab_rails['smtp_enable'] = {{ gitlab_smtp_enabled }}
    gitlab_rails['smtp_address'] = "{{ gitlab_smtp_address }}"
    gitlab_rails['smtp_port'] = {{ gitlab_smtp_port }}
    #gitlab_rails['smtp_user_name'] = "smtp user"
    #gitlab_rails['smtp_password'] = "smtp password"
    gitlab_rails['smtp_domain'] = "{{ gitlab_smtp_domain }}"
    #gitlab_rails['smtp_authentication'] = "login"
    gitlab_rails['smtp_enable_starttls_auto'] = true
    gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
    gitlab_rails['gitlab_email_from'] = 'gitlab@{{ gitlab_fqdn }}'
    gitlab_rails['gitlab_email_reply_to'] = 'noreply@{{ gitlab_fqdn }}'

container_user:
